- name: Setup gpg key
  apt_key:
    url: https://downloads.avax.network/avalanchego.gpg.key
    state: present

- name: Setup metalgo repo
  apt_repository:
    repo: deb https://downloads.avax.network/apt focal main
    state: present

- name: Setup golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports 
    state: present

- name: Install go
  apt:
    name: golang
    state: latest

- name: Update git clone
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_folder }}"
    version: "{{ tag }}"
    update: yes
    force: yes

- name: Setup systemd
  template:
    src: templates/metalgo.service.j2
    dest: /etc/systemd/system/metalgo.service
    mode: 0755

- name: Create metal user
  user:
    name: "{{ ava_user }}"
    shell: /bin/bash
    uid: 114
    group: "{{ ava_group }}"

- name: Create metal config dir
  file:
    path: /etc/metalgo
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create metal C config dir
  file:
    path: /etc/metalgo/C
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create metal log dir
  file:
    path: "{{ log_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create metal database dir
  file:
    path: "{{ db_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Build metalgo
  command: ./scripts/build.sh
  args:
    chdir: "{{ repo_folder }}"

- name: Copy metalgo binaries to the correct location
  command: cp build/metalgo /usr/local/bin/metalgo
  args:
    chdir: "{{ repo_folder }}"

- name: Configure avalanche 
  template:
    src: templates/conf.json.j2
    dest: /etc/metalgo/conf.json
    mode: 0644

- name: Configure avalanche C Chain
  template:
    src: templates/C/config.json.j2
    dest: /etc/metalgo/C/config.json
    mode: 0644

- name: Enable Metal
  systemd:
    name: metalgo
    enabled: yes
