---
ava_user: avalanche
ava_group: admin
network: mainnet
db_dir: /data/metalgo
log_dir: /var/log/metalgo
config_dir: /etc/metalgo
repo_url: https://github.com/MetalBlockchain/metalgo
repo_folder: /tmp/metalgo
